# Generated by Django 3.1.7 on 2021-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='customer_xid',
            field=models.TextField(default='', unique=True),
        ),
    ]
