# Generated by Django 3.1.7 on 2021-03-28 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallet_customer_xid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
