# Generated by Django 3.1.7 on 2021-03-28 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wallet_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_xid', models.TextField(default='', unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='token',
        ),
    ]
