# Generated by Django 3.1.7 on 2021-03-28 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210328_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockCustomerModel',
        ),
        migrations.AddField(
            model_name='wallet',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
