# Generated by Django 3.1.7 on 2021-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210328_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
