# Generated by Django 3.1.7 on 2021-03-28 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210328_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
