# Generated by Django 3.1.7 on 2021-03-28 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210328_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
