# Generated by Django 3.1.7 on 2021-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='enabled_at',
        ),
    ]
